### ISSUE TITLE
R code for natural breaks

### ISSUE THREAD

**Issue by arnfinn** [Helseatlas/shinymap#74]
To divide into Jenks natural breaks, we can either use 
- [classInt::classIntervals](https://www.rdocumentation.org/packages/classInt/versions/0.3-3/topics/classIntervals) or 
- [BAMMtools::getJenksBreaks](https://www.rdocumentation.org/packages/BAMMtools/versions/2.1.6/topics/getJenksBreaks). 

The latter is a C implementation of the first one, according to https://stackoverflow.com/a/56072902. We do not need the speed, so the first one is suffice.

**Comment by hannesigrun** [comment]
Har begynt. Gjort noen forsøksvise endringer i plot_variation.r som fungerer sånn noenlunde.
