### ISSUE TITLE
Lage datasett med data fra tidligere atlas

### ISSUE THREAD

**Issue by arnfinn** [Helseatlas/shinymap#75]
## Gjelder følgende atlas, både på norsk og engelsk

- [x] Dagkirurgi 2011-2013
- [x] Barn 2011-2014
- [x] Nyfødt 2009-2014
- [x] Eldre 2013-2015
- [x] Kols 2013-2015
- [x] Dagkirurgi 2013-2017
- [x] Ortopedi 2012-2016
- [x] Gynekologi 2015-2017
- [x] Fødselshjelp 2015-2017

## Momenter å vurdere

1. Ta med alle år og la R regne ut snittet etc.?
2. Slå sammen norsk og engelsk i samme datasett, med to ulike tekst-variabler?
3. Lese fra json-fil, excel-fil eller annet? I json og excel finnes ikke årsspesifikke data, så da blir det uaktuelt med punkt 1.
4. Legge dataene inn i annen pakke, slik at de kan brukes fra denne pakken ved å installere den andre pakken (noe ala `devtools::install_github("Helseatlas/data")`, `mydata <- data::kols`)

**Comment by arnfinn** [comment]
@knarfneslo Hva tenker du om dette?

**Comment by knarfneslo** [comment]
@arnfinn Hva tenker du om dette?
1. Har tatt med alle år og gjennomsnittet - rate for snitt er justert
2. Har lagd et norskt og ett engelsk datasett for dagkir - du kan jo se om det er slik du vil ha det?
3. Datasettene er lagret på server: helseatlas.data_dagkir_no og helseatlas.data_dagkir_en

**Comment by arnfinn** [comment]
![Screenshot 2019-05-15 at 14 00 51](https://user-images.githubusercontent.com/136346/57774127-fcc27180-7719-11e9-97d7-9ed85288d69a.png)

**Comment by arnfinn** [comment]
@knarfneslo la alle dataene inn som csv-filer her: https://github.com/Helseatlas/data/csv/

Disse csv-filene er konvertert til r-data, og kan brukes med følgende kode (eksemplifisert med kols-data):

```r
remotes::install_github("Helseatlas/data")
healthatlas_data <- data::kols
```
