### ISSUE TITLE
"data"-pakken  er ikkje tilgjengeleg i R versjon 3.6.0 

### ISSUE THREAD

**Issue by kiosvoll-HFD** [Helseatlas/shinymap#80]
Hei, har oppgradet til R version 3.6.0   Får ikkje lag til "data" pakke. 
 

> install.packages("data")
Installing package into ‘C:/Users/Acer/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘data’ is not available (for R version 3.6.0)

Har nokon erfaring med det? 

-Knut Ivar

**Comment by arnfinn** [comment]
Dette er vår egen pakke, så må installeres fra github. Noe ala (er på telefon, så kan ikke sjekke):

‘’’
remotes::install_github(“Helseatlas/data”)
‘’’

Det samme gjelder pakken ‘maps’.

**Comment by kiosvoll-HFD** [comment]
Hei,  eg er litt ukjent med korleis ting fugere i R.  Litt usikker på kor den hentear kodane når eg køyrer dette, men har gjort eit forsøk.   Installasjon av remotes gikk fint, men den neste kommandoen feila. Sjekk feilmelding. 


install.packages("remotes")

remotes::install_github("Helseatlas/data")


> remotes::install_github("Helseatlas/data")
Error in curl::curl_fetch_memory(url, handle = h) : 
  Timeout was reached: Connection timed out after 10016 milliseconds



-Knut Ivar

**Comment by arnfinn** [comment]
Muligens det har noe med proxy å gjøre. Ligger noe (utdatert?) dokumentasjon her: https://skde-analyse.github.io/dokumentasjon/r.html#rstudio-og-github-pakker

`devtools::install_github` gjør sannsynligvis det samme som `remotes::install_github` (det kan virke som de deler opp `devtools` i flere pakker).

**Comment by areedv** [comment]
Ja, bruk ```devtools::install_github```. I tilfelle man er bak en proxy så kan man definere denne med miljøvariable i R, eksempelvis ```Sys.setenv(http_proxy="din.proxy.url:port")``` og ev også ```Sys.setenv(https_proxy="din.proxy.url:port")```. For å bevare slike innstillinger ved restart av R kan de samme miljøvariablene settes i fila .Renviron som R leser ved oppstart (men da uten ```Sys.setenv()```
